
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the cloudsifterData datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.cloudsifterData cloudsifterData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.cloudsifterData);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.cloudsifterData;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.cloudsifterData> cloudsifterData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.cloudsifterData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.cloudsifterData>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.cloudsifterData>.Entry
                    cloudsifterData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.cloudsifterData>.Entry(
                        "cloudsifterData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._cloudsifterData_Stub);
                private static void _cloudsifterData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.cloudsifterData>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._cloudsifterData, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.cloudsifterData>.Data _cloudsifterData;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the cloudsifterData datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class cloudsifterData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public cloudsifterData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Categories entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Category> Categories
        {
            get
            {
                return global::LightSwitchApplication.cloudsifterData.DetailsClass.GetValue(this, global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.Categories);
            }
        }
        
        /// <summary>
        /// Gets the Links entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Link> Links
        {
            get
            {
                return global::LightSwitchApplication.cloudsifterData.DetailsClass.GetValue(this, global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.Links);
            }
        }
        
        /// <summary>
        /// Gets the LinkCategories entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LinkCategory> LinkCategories
        {
            get
            {
                return global::LightSwitchApplication.cloudsifterData.DetailsClass.GetValue(this, global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.LinkCategories);
            }
        }
        
        /// <summary>
        /// Gets the LinkSpotters entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LinkSpotter> LinkSpotters
        {
            get
            {
                return global::LightSwitchApplication.cloudsifterData.DetailsClass.GetValue(this, global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.LinkSpotters);
            }
        }
        
        /// <summary>
        /// Gets the LinkSpotterLinks entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LinkSpotterLink> LinkSpotterLinks
        {
            get
            {
                return global::LightSwitchApplication.cloudsifterData.DetailsClass.GetValue(this, global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.LinkSpotterLinks);
            }
        }
        
        /// <summary>
        /// Gets the LinkSpotterUnprocessedLinks entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LinkSpotterUnprocessedLink> LinkSpotterUnprocessedLinks
        {
            get
            {
                return global::LightSwitchApplication.cloudsifterData.DetailsClass.GetValue(this, global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.LinkSpotterUnprocessedLinks);
            }
        }
        
        /// <summary>
        /// Gets the Newsletters entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Newsletter> Newsletters
        {
            get
            {
                return global::LightSwitchApplication.cloudsifterData.DetailsClass.GetValue(this, global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.Newsletters);
            }
        }
        
        /// <summary>
        /// Gets the UnprocessedLinks entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UnprocessedLink> UnprocessedLinks
        {
            get
            {
                return global::LightSwitchApplication.cloudsifterData.DetailsClass.GetValue(this, global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.UnprocessedLinks);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Category Categories_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Categories_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Category Categories_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Categories_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Link Links_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Links_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Link Links_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Links_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="LinkId">
        /// The value of the 'LinkId' key property of the entity to retrieve.
        /// </param>
        /// <param name="CategoryId">
        /// The value of the 'CategoryId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.LinkCategory LinkCategories_Single(global::System.Nullable<int> LinkId, global::System.Nullable<int> CategoryId)
        {
            return this.Details.Methods.LinkCategories_Single.CreateInvocation(LinkId, CategoryId).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="LinkId">
        /// The value of the 'LinkId' key property of the entity to retrieve.
        /// </param>
        /// <param name="CategoryId">
        /// The value of the 'CategoryId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.LinkCategory LinkCategories_SingleOrDefault(global::System.Nullable<int> LinkId, global::System.Nullable<int> CategoryId)
        {
            return this.Details.Methods.LinkCategories_SingleOrDefault.CreateInvocation(LinkId, CategoryId).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.LinkSpotter LinkSpotters_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.LinkSpotters_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.LinkSpotter LinkSpotters_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.LinkSpotters_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="LinkSpotterId">
        /// The value of the 'LinkSpotterId' key property of the entity to retrieve.
        /// </param>
        /// <param name="LinkId">
        /// The value of the 'LinkId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.LinkSpotterLink LinkSpotterLinks_Single(global::System.Nullable<int> LinkSpotterId, global::System.Nullable<int> LinkId)
        {
            return this.Details.Methods.LinkSpotterLinks_Single.CreateInvocation(LinkSpotterId, LinkId).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="LinkSpotterId">
        /// The value of the 'LinkSpotterId' key property of the entity to retrieve.
        /// </param>
        /// <param name="LinkId">
        /// The value of the 'LinkId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.LinkSpotterLink LinkSpotterLinks_SingleOrDefault(global::System.Nullable<int> LinkSpotterId, global::System.Nullable<int> LinkId)
        {
            return this.Details.Methods.LinkSpotterLinks_SingleOrDefault.CreateInvocation(LinkSpotterId, LinkId).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="LinkSpotterId">
        /// The value of the 'LinkSpotterId' key property of the entity to retrieve.
        /// </param>
        /// <param name="UnprocessedLinkId">
        /// The value of the 'UnprocessedLinkId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.LinkSpotterUnprocessedLink LinkSpotterUnprocessedLinks_Single(global::System.Nullable<int> LinkSpotterId, global::System.Nullable<int> UnprocessedLinkId)
        {
            return this.Details.Methods.LinkSpotterUnprocessedLinks_Single.CreateInvocation(LinkSpotterId, UnprocessedLinkId).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="LinkSpotterId">
        /// The value of the 'LinkSpotterId' key property of the entity to retrieve.
        /// </param>
        /// <param name="UnprocessedLinkId">
        /// The value of the 'UnprocessedLinkId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.LinkSpotterUnprocessedLink LinkSpotterUnprocessedLinks_SingleOrDefault(global::System.Nullable<int> LinkSpotterId, global::System.Nullable<int> UnprocessedLinkId)
        {
            return this.Details.Methods.LinkSpotterUnprocessedLinks_SingleOrDefault.CreateInvocation(LinkSpotterId, UnprocessedLinkId).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Newsletter Newsletters_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Newsletters_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Newsletter Newsletters_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Newsletters_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.UnprocessedLink UnprocessedLinks_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.UnprocessedLinks_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.UnprocessedLink UnprocessedLinks_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.UnprocessedLinks_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySet, global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.Categories_Single;
                var initializePropertyEntry = global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.Categories;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category> Categories_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.Categories_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category> Categories_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.Categories_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link> Links_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.Links_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link> Links_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.Links_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory> LinkCategories_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.LinkCategories_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory> LinkCategories_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.LinkCategories_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter> LinkSpotters_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.LinkSpotters_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter> LinkSpotters_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.LinkSpotters_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink> LinkSpotterLinks_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.LinkSpotterLinks_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink> LinkSpotterLinks_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.LinkSpotterLinks_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink> LinkSpotterUnprocessedLinks_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.LinkSpotterUnprocessedLinks_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink> LinkSpotterUnprocessedLinks_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.LinkSpotterUnprocessedLinks_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter> Newsletters_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.Newsletters_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter> Newsletters_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.Newsletters_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink> UnprocessedLinks_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.UnprocessedLinks_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink> UnprocessedLinks_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties.UnprocessedLinks_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category> Categories
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.Categories) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link> Links
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.Links) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory> LinkCategories
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.LinkCategories) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter> LinkSpotters
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.LinkSpotters) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink> LinkSpotterLinks
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.LinkSpotterLinks) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink> LinkSpotterUnprocessedLinks
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.LinkSpotterUnprocessedLinks) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter> Newsletters
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.Newsletters) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink> UnprocessedLinks
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties.UnprocessedLinks) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>.Entry
                    Categories_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>.Entry(
                        "Categories_Single",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._Categories_Single_Stub);
                private static void _Categories_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._Categories_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>.Entry
                    Categories_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>.Entry(
                        "Categories_SingleOrDefault",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._Categories_SingleOrDefault_Stub);
                private static void _Categories_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._Categories_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>.Entry
                    Links_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>.Entry(
                        "Links_Single",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._Links_Single_Stub);
                private static void _Links_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._Links_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>.Entry
                    Links_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>.Entry(
                        "Links_SingleOrDefault",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._Links_SingleOrDefault_Stub);
                private static void _Links_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._Links_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>.Entry
                    LinkCategories_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>.Entry(
                        "LinkCategories_Single",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._LinkCategories_Single_Stub);
                private static void _LinkCategories_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkCategories_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>.Entry
                    LinkCategories_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>.Entry(
                        "LinkCategories_SingleOrDefault",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._LinkCategories_SingleOrDefault_Stub);
                private static void _LinkCategories_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkCategories_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Entry
                    LinkSpotters_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Entry(
                        "LinkSpotters_Single",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._LinkSpotters_Single_Stub);
                private static void _LinkSpotters_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotters_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Entry
                    LinkSpotters_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Entry(
                        "LinkSpotters_SingleOrDefault",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._LinkSpotters_SingleOrDefault_Stub);
                private static void _LinkSpotters_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotters_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Entry
                    LinkSpotterLinks_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Entry(
                        "LinkSpotterLinks_Single",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._LinkSpotterLinks_Single_Stub);
                private static void _LinkSpotterLinks_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotterLinks_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Entry
                    LinkSpotterLinks_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Entry(
                        "LinkSpotterLinks_SingleOrDefault",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._LinkSpotterLinks_SingleOrDefault_Stub);
                private static void _LinkSpotterLinks_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotterLinks_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Entry
                    LinkSpotterUnprocessedLinks_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Entry(
                        "LinkSpotterUnprocessedLinks_Single",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._LinkSpotterUnprocessedLinks_Single_Stub);
                private static void _LinkSpotterUnprocessedLinks_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotterUnprocessedLinks_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Entry
                    LinkSpotterUnprocessedLinks_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Entry(
                        "LinkSpotterUnprocessedLinks_SingleOrDefault",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._LinkSpotterUnprocessedLinks_SingleOrDefault_Stub);
                private static void _LinkSpotterUnprocessedLinks_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotterUnprocessedLinks_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>.Entry
                    Newsletters_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>.Entry(
                        "Newsletters_Single",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._Newsletters_Single_Stub);
                private static void _Newsletters_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._Newsletters_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>.Entry
                    Newsletters_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>.Entry(
                        "Newsletters_SingleOrDefault",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._Newsletters_SingleOrDefault_Stub);
                private static void _Newsletters_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._Newsletters_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>.Entry
                    UnprocessedLinks_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>.Entry(
                        "UnprocessedLinks_Single",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._UnprocessedLinks_Single_Stub);
                private static void _UnprocessedLinks_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._UnprocessedLinks_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>.Entry
                    UnprocessedLinks_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>.Entry(
                        "UnprocessedLinks_SingleOrDefault",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.MethodSetProperties._UnprocessedLinks_SingleOrDefault_Stub);
                private static void _UnprocessedLinks_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._UnprocessedLinks_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>.Entry
                    Categories = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>.Entry(
                        "Categories",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties._Categories_Stub);
                private static void _Categories_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._Categories, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>.Entry
                    Links = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>.Entry(
                        "Links",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties._Links_Stub);
                private static void _Links_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._Links, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>.Entry
                    LinkCategories = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>.Entry(
                        "LinkCategories",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties._LinkCategories_Stub);
                private static void _LinkCategories_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkCategories, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Entry
                    LinkSpotters = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Entry(
                        "LinkSpotters",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties._LinkSpotters_Stub);
                private static void _LinkSpotters_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotters, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Entry
                    LinkSpotterLinks = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Entry(
                        "LinkSpotterLinks",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties._LinkSpotterLinks_Stub);
                private static void _LinkSpotterLinks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotterLinks, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Entry
                    LinkSpotterUnprocessedLinks = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Entry(
                        "LinkSpotterUnprocessedLinks",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties._LinkSpotterUnprocessedLinks_Stub);
                private static void _LinkSpotterUnprocessedLinks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotterUnprocessedLinks, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>.Entry
                    Newsletters = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>.Entry(
                        "Newsletters",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties._Newsletters_Stub);
                private static void _Newsletters_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._Newsletters, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>.Entry
                    UnprocessedLinks = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>.Entry(
                        "UnprocessedLinks",
                        global::LightSwitchApplication.cloudsifterData.DetailsClass.PropertySetProperties._UnprocessedLinks_Stub);
                private static void _UnprocessedLinks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.cloudsifterData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>.Data> c, global::LightSwitchApplication.cloudsifterData.DetailsClass d, object sf)
                {
                    c(d, ref d._UnprocessedLinks, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>.Data _Categories;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>.Data _Links;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>.Data _LinkCategories;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Data _LinkSpotters;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Data _LinkSpotterLinks;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Data _LinkSpotterUnprocessedLinks;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>.Data _Newsletters;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>.Data _UnprocessedLinks;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>.Data _Categories_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Category>.Data _Categories_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>.Data _Links_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Link>.Data _Links_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>.Data _LinkCategories_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkCategory>.Data _LinkCategories_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Data _LinkSpotters_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Data _LinkSpotters_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Data _LinkSpotterLinks_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Data _LinkSpotterLinks_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Data _LinkSpotterUnprocessedLinks_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Data _LinkSpotterUnprocessedLinks_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>.Data _Newsletters_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.Newsletter>.Data _Newsletters_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>.Data _UnprocessedLinks_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.cloudsifterData, global::LightSwitchApplication.cloudsifterData.DetailsClass, global::LightSwitchApplication.UnprocessedLink>.Data _UnprocessedLinks_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
