

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Link : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Link entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Link()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Link(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Link> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Link.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Link_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Link_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Link.DetailsClass.GetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.Link.DetailsClass.GetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.Link.DetailsClass.SetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string URL
        {
            get
            {
                return global::LightSwitchApplication.Link.DetailsClass.GetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.URL);
            }
            set
            {
                global::LightSwitchApplication.Link.DetailsClass.SetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.URL, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void URL_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void URL_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void URL_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.Link.DetailsClass.GetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.Link.DetailsClass.SetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PlugImageURL150x150
        {
            get
            {
                return global::LightSwitchApplication.Link.DetailsClass.GetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.PlugImageURL150x150);
            }
            set
            {
                global::LightSwitchApplication.Link.DetailsClass.SetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.PlugImageURL150x150, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlugImageURL150x150_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlugImageURL150x150_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlugImageURL150x150_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Link> Links
        {
            get
            {
                return global::LightSwitchApplication.Link.DetailsClass.GetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Links);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Link> LinksQuery
        {
            get
            {
                return global::LightSwitchApplication.Link.DetailsClass.GetQuery(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Links);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Link Link1
        {
            get
            {
                return global::LightSwitchApplication.Link.DetailsClass.GetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Link1);
            }
            set
            {
                global::LightSwitchApplication.Link.DetailsClass.SetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Link1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Link1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Link1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Link1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Newsletter Newsletter
        {
            get
            {
                return global::LightSwitchApplication.Link.DetailsClass.GetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Newsletter);
            }
            set
            {
                global::LightSwitchApplication.Link.DetailsClass.SetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Newsletter, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Newsletter_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Newsletter_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Newsletter_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.LinkCategory> LinkCategories
        {
            get
            {
                return global::LightSwitchApplication.Link.DetailsClass.GetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.LinkCategories);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.LinkCategory> LinkCategoriesQuery
        {
            get
            {
                return global::LightSwitchApplication.Link.DetailsClass.GetQuery(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.LinkCategories);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.LinkSpotterLink> LinkSpotterLinks
        {
            get
            {
                return global::LightSwitchApplication.Link.DetailsClass.GetValue(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.LinkSpotterLinks);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.LinkSpotterLink> LinkSpotterLinksQuery
        {
            get
            {
                return global::LightSwitchApplication.Link.DetailsClass.GetQuery(this, global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.LinkSpotterLinks);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Link,
                global::LightSwitchApplication.Link.DetailsClass,
                global::LightSwitchApplication.Link.DetailsClass.IImplementation,
                global::LightSwitchApplication.Link.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass>.Entry
                __LinkEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass>.Entry(
                    global::LightSwitchApplication.Link.DetailsClass.__Link_CreateNew,
                    global::LightSwitchApplication.Link.DetailsClass.__Link_Created,
                    global::LightSwitchApplication.Link.DetailsClass.__Link_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Link __Link_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Link> es)
            {
                return new global::LightSwitchApplication.Link(es);
            }
            private static void __Link_Created(global::LightSwitchApplication.Link e)
            {
                e.Link_Created();
            }
            private static bool __Link_AllowSaveWithErrors(global::LightSwitchApplication.Link e)
            {
                bool result = false;
                e.Link_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Link.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string> URL
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.URL) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string> PlugImageURL150x150
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.PlugImageURL150x150) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Link> Links
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Links) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Link>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Link> Link1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Link1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Link>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Newsletter> Newsletter
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Newsletter) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Newsletter>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.LinkCategory> LinkCategories
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.LinkCategories) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.LinkCategory>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.LinkSpotterLink> LinkSpotterLinks
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.LinkSpotterLinks) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Title { get; set; }
                new string URL { get; set; }
                new string Description { get; set; }
                new string PlugImageURL150x150 { get; set; }
                new global::System.Collections.IEnumerable Links { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Link1 { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Newsletter { get; set; }
                new global::System.Collections.IEnumerable LinkCategories { get; }
                new global::System.Collections.IEnumerable LinkSpotterLinks { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Link.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, int>.Data> c, global::LightSwitchApplication.Link.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Link e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Link e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Link e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Link.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Data> c, global::LightSwitchApplication.Link.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.Link e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.Link e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.Link.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.Link e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Entry
                    URL = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Entry(
                        "URL",
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._URL_Stub,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._URL_ComputeIsReadOnly,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._URL_Validate,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._URL_GetImplementationValue,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._URL_SetImplementationValue,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._URL_OnValueChanged);
                private static void _URL_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Link.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Data> c, global::LightSwitchApplication.Link.DetailsClass d, object sf)
                {
                    c(d, ref d._URL, sf);
                }
                private static bool _URL_ComputeIsReadOnly(global::LightSwitchApplication.Link e)
                {
                    bool result = false;
                    e.URL_IsReadOnly(ref result);
                    return result;
                }
                private static void _URL_Validate(global::LightSwitchApplication.Link e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.URL_Validate(r);
                }
                private static string _URL_GetImplementationValue(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.ImplementationEntity.URL;
                }
                private static void _URL_SetImplementationValue(global::LightSwitchApplication.Link.DetailsClass d, string v)
                {
                    d.ImplementationEntity.URL = v;
                }
                private static void _URL_OnValueChanged(global::LightSwitchApplication.Link e)
                {
                    e.URL_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Link.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Data> c, global::LightSwitchApplication.Link.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.Link e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.Link e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.Link.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.Link e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Entry
                    PlugImageURL150x150 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Entry(
                        "PlugImageURL150x150",
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._PlugImageURL150x150_Stub,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._PlugImageURL150x150_ComputeIsReadOnly,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._PlugImageURL150x150_Validate,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._PlugImageURL150x150_GetImplementationValue,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._PlugImageURL150x150_SetImplementationValue,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._PlugImageURL150x150_OnValueChanged);
                private static void _PlugImageURL150x150_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Link.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Data> c, global::LightSwitchApplication.Link.DetailsClass d, object sf)
                {
                    c(d, ref d._PlugImageURL150x150, sf);
                }
                private static bool _PlugImageURL150x150_ComputeIsReadOnly(global::LightSwitchApplication.Link e)
                {
                    bool result = false;
                    e.PlugImageURL150x150_IsReadOnly(ref result);
                    return result;
                }
                private static void _PlugImageURL150x150_Validate(global::LightSwitchApplication.Link e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PlugImageURL150x150_Validate(r);
                }
                private static string _PlugImageURL150x150_GetImplementationValue(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.ImplementationEntity.PlugImageURL150x150;
                }
                private static void _PlugImageURL150x150_SetImplementationValue(global::LightSwitchApplication.Link.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PlugImageURL150x150 = v;
                }
                private static void _PlugImageURL150x150_OnValueChanged(global::LightSwitchApplication.Link e)
                {
                    e.PlugImageURL150x150_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Link>.Entry
                    Links = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Link>.Entry(
                        "Links",
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Links_Stub,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Links_GetReferencedEntities,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Links_GetEntityCollection);
                private static void _Links_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Link.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Link>.Data> c, global::LightSwitchApplication.Link.DetailsClass d, object sf)
                {
                    c(d, ref d._Links, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Link> _Links_GetReferencedEntities(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass>(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Links, ref d._Links);
                }
                private static global::System.Collections.IEnumerable _Links_GetEntityCollection(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.ImplementationEntity.Links;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Link>.Entry
                    Link1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Link>.Entry(
                        "Link1",
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Link1_Stub,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Link1_ComputeIsReadOnly,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Link1_Validate,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Link1_GetCoreImplementationValue,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Link1_GetImplementationValue,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Link1_SetImplementationValue,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Link1_Refresh,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Link1_OnValueChanged);
                private static void _Link1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Link.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Link>.Data> c, global::LightSwitchApplication.Link.DetailsClass d, object sf)
                {
                    c(d, ref d._Link1, sf);
                }
                private static bool _Link1_ComputeIsReadOnly(global::LightSwitchApplication.Link e)
                {
                    bool result = false;
                    e.Link1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Link1_Validate(global::LightSwitchApplication.Link e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Link1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Link1_GetCoreImplementationValue(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.ImplementationEntity.Link1;
                }
                private static global::LightSwitchApplication.Link _Link1_GetImplementationValue(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass>(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Link1, ref d._Link1);
                }
                private static void _Link1_SetImplementationValue(global::LightSwitchApplication.Link.DetailsClass d, global::LightSwitchApplication.Link v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Link1, ref d._Link1, (i, ev) => i.Link1 = ev, v);
                }
                private static void _Link1_Refresh(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Link1, ref d._Link1);
                }
                private static void _Link1_OnValueChanged(global::LightSwitchApplication.Link e)
                {
                    e.Link1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Newsletter>.Entry
                    Newsletter = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Newsletter>.Entry(
                        "Newsletter",
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Newsletter_Stub,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Newsletter_ComputeIsReadOnly,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Newsletter_Validate,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Newsletter_GetCoreImplementationValue,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Newsletter_GetImplementationValue,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Newsletter_SetImplementationValue,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Newsletter_Refresh,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._Newsletter_OnValueChanged);
                private static void _Newsletter_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Link.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Newsletter>.Data> c, global::LightSwitchApplication.Link.DetailsClass d, object sf)
                {
                    c(d, ref d._Newsletter, sf);
                }
                private static bool _Newsletter_ComputeIsReadOnly(global::LightSwitchApplication.Link e)
                {
                    bool result = false;
                    e.Newsletter_IsReadOnly(ref result);
                    return result;
                }
                private static void _Newsletter_Validate(global::LightSwitchApplication.Link e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Newsletter_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Newsletter_GetCoreImplementationValue(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.ImplementationEntity.Newsletter;
                }
                private static global::LightSwitchApplication.Newsletter _Newsletter_GetImplementationValue(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass>(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Newsletter, ref d._Newsletter);
                }
                private static void _Newsletter_SetImplementationValue(global::LightSwitchApplication.Link.DetailsClass d, global::LightSwitchApplication.Newsletter v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Newsletter, ref d._Newsletter, (i, ev) => i.Newsletter = ev, v);
                }
                private static void _Newsletter_Refresh(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.Newsletter, ref d._Newsletter);
                }
                private static void _Newsletter_OnValueChanged(global::LightSwitchApplication.Link e)
                {
                    e.Newsletter_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.LinkCategory>.Entry
                    LinkCategories = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.LinkCategory>.Entry(
                        "LinkCategories",
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._LinkCategories_Stub,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._LinkCategories_GetReferencedEntities,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._LinkCategories_GetEntityCollection);
                private static void _LinkCategories_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Link.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.LinkCategory>.Data> c, global::LightSwitchApplication.Link.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkCategories, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.LinkCategory> _LinkCategories_GetReferencedEntities(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.LinkCategory, global::LightSwitchApplication.LinkCategory.DetailsClass>(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.LinkCategories, ref d._LinkCategories);
                }
                private static global::System.Collections.IEnumerable _LinkCategories_GetEntityCollection(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.ImplementationEntity.LinkCategories;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Entry
                    LinkSpotterLinks = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Entry(
                        "LinkSpotterLinks",
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._LinkSpotterLinks_Stub,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._LinkSpotterLinks_GetReferencedEntities,
                        global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties._LinkSpotterLinks_GetEntityCollection);
                private static void _LinkSpotterLinks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Link.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Data> c, global::LightSwitchApplication.Link.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotterLinks, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.LinkSpotterLink> _LinkSpotterLinks_GetReferencedEntities(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass>(global::LightSwitchApplication.Link.DetailsClass.PropertySetProperties.LinkSpotterLinks, ref d._LinkSpotterLinks);
                }
                private static global::System.Collections.IEnumerable _LinkSpotterLinks_GetEntityCollection(global::LightSwitchApplication.Link.DetailsClass d)
                {
                    return d.ImplementationEntity.LinkSpotterLinks;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Data _URL;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, string>.Data _PlugImageURL150x150;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Link>.Data _Links;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Link>.Data _Link1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.Newsletter>.Data _Newsletter;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.LinkCategory>.Data _LinkCategories;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Data _LinkSpotterLinks;
            
        }
    
        #endregion
    }
    
    #endregion
}
