

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class LinkSpotterLink : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the LinkSpotterLink entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LinkSpotterLink()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LinkSpotterLink(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LinkSpotterLink> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.LinkSpotterLink.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LinkSpotterLink_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LinkSpotterLink_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int LinkSpotterId
        {
            get
            {
                return global::LightSwitchApplication.LinkSpotterLink.DetailsClass.GetValue(this, global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.LinkSpotterId);
            }
            set
            {
                global::LightSwitchApplication.LinkSpotterLink.DetailsClass.SetValue(this, global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.LinkSpotterId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LinkSpotterId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LinkSpotterId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LinkSpotterId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int LinkId
        {
            get
            {
                return global::LightSwitchApplication.LinkSpotterLink.DetailsClass.GetValue(this, global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.LinkId);
            }
            set
            {
                global::LightSwitchApplication.LinkSpotterLink.DetailsClass.SetValue(this, global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.LinkId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LinkId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LinkId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LinkId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> TimeSpotted
        {
            get
            {
                return global::LightSwitchApplication.LinkSpotterLink.DetailsClass.GetValue(this, global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.TimeSpotted);
            }
            set
            {
                global::LightSwitchApplication.LinkSpotterLink.DetailsClass.SetValue(this, global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.TimeSpotted, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TimeSpotted_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TimeSpotted_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TimeSpotted_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Link Link
        {
            get
            {
                return global::LightSwitchApplication.LinkSpotterLink.DetailsClass.GetValue(this, global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.Link);
            }
            set
            {
                global::LightSwitchApplication.LinkSpotterLink.DetailsClass.SetValue(this, global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.Link, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Link_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Link_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Link_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.LinkSpotter LinkSpotter
        {
            get
            {
                return global::LightSwitchApplication.LinkSpotterLink.DetailsClass.GetValue(this, global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.LinkSpotter);
            }
            set
            {
                global::LightSwitchApplication.LinkSpotterLink.DetailsClass.SetValue(this, global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.LinkSpotter, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LinkSpotter_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LinkSpotter_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LinkSpotter_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.LinkSpotterLink,
                global::LightSwitchApplication.LinkSpotterLink.DetailsClass,
                global::LightSwitchApplication.LinkSpotterLink.DetailsClass.IImplementation,
                global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.LinkSpotterId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass>.Entry
                __LinkSpotterLinkEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass>.Entry(
                    global::LightSwitchApplication.LinkSpotterLink.DetailsClass.__LinkSpotterLink_CreateNew,
                    global::LightSwitchApplication.LinkSpotterLink.DetailsClass.__LinkSpotterLink_Created,
                    global::LightSwitchApplication.LinkSpotterLink.DetailsClass.__LinkSpotterLink_AllowSaveWithErrors);
            private static global::LightSwitchApplication.LinkSpotterLink __LinkSpotterLink_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LinkSpotterLink> es)
            {
                return new global::LightSwitchApplication.LinkSpotterLink(es);
            }
            private static void __LinkSpotterLink_Created(global::LightSwitchApplication.LinkSpotterLink e)
            {
                e.LinkSpotterLink_Created();
            }
            private static bool __LinkSpotterLink_AllowSaveWithErrors(global::LightSwitchApplication.LinkSpotterLink e)
            {
                bool result = false;
                e.LinkSpotterLink_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, int> LinkSpotterId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.LinkSpotterId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, int> LinkId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.LinkId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::System.Nullable<global::System.DateTime>> TimeSpotted
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.TimeSpotted) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::LightSwitchApplication.Link> Link
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.Link) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::LightSwitchApplication.Link>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::LightSwitchApplication.LinkSpotter> LinkSpotter
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.LinkSpotter) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::LightSwitchApplication.LinkSpotter>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int LinkSpotterId { get; set; }
                new int LinkId { get; set; }
                new global::System.Nullable<global::System.DateTime> TimeSpotted { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Link { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation LinkSpotter { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, int>.Entry
                    LinkSpotterId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, int>.Entry(
                        "LinkSpotterId",
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkSpotterId_Stub,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkSpotterId_ComputeIsReadOnly,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkSpotterId_Validate,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkSpotterId_GetImplementationValue,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkSpotterId_SetImplementationValue,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkSpotterId_OnValueChanged);
                private static void _LinkSpotterId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, int>.Data> c, global::LightSwitchApplication.LinkSpotterLink.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotterId, sf);
                }
                private static bool _LinkSpotterId_ComputeIsReadOnly(global::LightSwitchApplication.LinkSpotterLink e)
                {
                    bool result = false;
                    e.LinkSpotterId_IsReadOnly(ref result);
                    return result;
                }
                private static void _LinkSpotterId_Validate(global::LightSwitchApplication.LinkSpotterLink e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LinkSpotterId_Validate(r);
                }
                private static int _LinkSpotterId_GetImplementationValue(global::LightSwitchApplication.LinkSpotterLink.DetailsClass d)
                {
                    return d.ImplementationEntity.LinkSpotterId;
                }
                private static void _LinkSpotterId_SetImplementationValue(global::LightSwitchApplication.LinkSpotterLink.DetailsClass d, int v)
                {
                    d.ImplementationEntity.LinkSpotterId = v;
                }
                private static void _LinkSpotterId_OnValueChanged(global::LightSwitchApplication.LinkSpotterLink e)
                {
                    e.LinkSpotterId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, int>.Entry
                    LinkId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, int>.Entry(
                        "LinkId",
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkId_Stub,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkId_ComputeIsReadOnly,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkId_Validate,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkId_GetImplementationValue,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkId_SetImplementationValue,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkId_OnValueChanged);
                private static void _LinkId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, int>.Data> c, global::LightSwitchApplication.LinkSpotterLink.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkId, sf);
                }
                private static bool _LinkId_ComputeIsReadOnly(global::LightSwitchApplication.LinkSpotterLink e)
                {
                    bool result = false;
                    e.LinkId_IsReadOnly(ref result);
                    return result;
                }
                private static void _LinkId_Validate(global::LightSwitchApplication.LinkSpotterLink e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LinkId_Validate(r);
                }
                private static int _LinkId_GetImplementationValue(global::LightSwitchApplication.LinkSpotterLink.DetailsClass d)
                {
                    return d.ImplementationEntity.LinkId;
                }
                private static void _LinkId_SetImplementationValue(global::LightSwitchApplication.LinkSpotterLink.DetailsClass d, int v)
                {
                    d.ImplementationEntity.LinkId = v;
                }
                private static void _LinkId_OnValueChanged(global::LightSwitchApplication.LinkSpotterLink e)
                {
                    e.LinkId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    TimeSpotted = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "TimeSpotted",
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._TimeSpotted_Stub,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._TimeSpotted_ComputeIsReadOnly,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._TimeSpotted_Validate,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._TimeSpotted_GetImplementationValue,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._TimeSpotted_SetImplementationValue,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._TimeSpotted_OnValueChanged);
                private static void _TimeSpotted_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.LinkSpotterLink.DetailsClass d, object sf)
                {
                    c(d, ref d._TimeSpotted, sf);
                }
                private static bool _TimeSpotted_ComputeIsReadOnly(global::LightSwitchApplication.LinkSpotterLink e)
                {
                    bool result = false;
                    e.TimeSpotted_IsReadOnly(ref result);
                    return result;
                }
                private static void _TimeSpotted_Validate(global::LightSwitchApplication.LinkSpotterLink e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TimeSpotted_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _TimeSpotted_GetImplementationValue(global::LightSwitchApplication.LinkSpotterLink.DetailsClass d)
                {
                    return d.ImplementationEntity.TimeSpotted;
                }
                private static void _TimeSpotted_SetImplementationValue(global::LightSwitchApplication.LinkSpotterLink.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.TimeSpotted = global::LightSwitchApplication.LinkSpotterLink.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _TimeSpotted_OnValueChanged(global::LightSwitchApplication.LinkSpotterLink e)
                {
                    e.TimeSpotted_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::LightSwitchApplication.Link>.Entry
                    Link = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::LightSwitchApplication.Link>.Entry(
                        "Link",
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._Link_Stub,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._Link_ComputeIsReadOnly,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._Link_Validate,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._Link_GetCoreImplementationValue,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._Link_GetImplementationValue,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._Link_SetImplementationValue,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._Link_Refresh,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._Link_OnValueChanged);
                private static void _Link_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::LightSwitchApplication.Link>.Data> c, global::LightSwitchApplication.LinkSpotterLink.DetailsClass d, object sf)
                {
                    c(d, ref d._Link, sf);
                }
                private static bool _Link_ComputeIsReadOnly(global::LightSwitchApplication.LinkSpotterLink e)
                {
                    bool result = false;
                    e.Link_IsReadOnly(ref result);
                    return result;
                }
                private static void _Link_Validate(global::LightSwitchApplication.LinkSpotterLink e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Link_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Link_GetCoreImplementationValue(global::LightSwitchApplication.LinkSpotterLink.DetailsClass d)
                {
                    return d.ImplementationEntity.Link;
                }
                private static global::LightSwitchApplication.Link _Link_GetImplementationValue(global::LightSwitchApplication.LinkSpotterLink.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass>(global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.Link, ref d._Link);
                }
                private static void _Link_SetImplementationValue(global::LightSwitchApplication.LinkSpotterLink.DetailsClass d, global::LightSwitchApplication.Link v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.Link, ref d._Link, (i, ev) => i.Link = ev, v);
                }
                private static void _Link_Refresh(global::LightSwitchApplication.LinkSpotterLink.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.Link, ref d._Link);
                }
                private static void _Link_OnValueChanged(global::LightSwitchApplication.LinkSpotterLink e)
                {
                    e.Link_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Entry
                    LinkSpotter = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Entry(
                        "LinkSpotter",
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkSpotter_Stub,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkSpotter_ComputeIsReadOnly,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkSpotter_Validate,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkSpotter_GetCoreImplementationValue,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkSpotter_GetImplementationValue,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkSpotter_SetImplementationValue,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkSpotter_Refresh,
                        global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties._LinkSpotter_OnValueChanged);
                private static void _LinkSpotter_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Data> c, global::LightSwitchApplication.LinkSpotterLink.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotter, sf);
                }
                private static bool _LinkSpotter_ComputeIsReadOnly(global::LightSwitchApplication.LinkSpotterLink e)
                {
                    bool result = false;
                    e.LinkSpotter_IsReadOnly(ref result);
                    return result;
                }
                private static void _LinkSpotter_Validate(global::LightSwitchApplication.LinkSpotterLink e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LinkSpotter_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _LinkSpotter_GetCoreImplementationValue(global::LightSwitchApplication.LinkSpotterLink.DetailsClass d)
                {
                    return d.ImplementationEntity.LinkSpotter;
                }
                private static global::LightSwitchApplication.LinkSpotter _LinkSpotter_GetImplementationValue(global::LightSwitchApplication.LinkSpotterLink.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass>(global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.LinkSpotter, ref d._LinkSpotter);
                }
                private static void _LinkSpotter_SetImplementationValue(global::LightSwitchApplication.LinkSpotterLink.DetailsClass d, global::LightSwitchApplication.LinkSpotter v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.LinkSpotter, ref d._LinkSpotter, (i, ev) => i.LinkSpotter = ev, v);
                }
                private static void _LinkSpotter_Refresh(global::LightSwitchApplication.LinkSpotterLink.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.LinkSpotterLink.DetailsClass.PropertySetProperties.LinkSpotter, ref d._LinkSpotter);
                }
                private static void _LinkSpotter_OnValueChanged(global::LightSwitchApplication.LinkSpotterLink e)
                {
                    e.LinkSpotter_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, int>.Data _LinkSpotterId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, int>.Data _LinkId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _TimeSpotted;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::LightSwitchApplication.Link>.Data _Link;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass, global::LightSwitchApplication.LinkSpotter>.Data _LinkSpotter;
            
        }
    
        #endregion
    }
    
    #endregion
}
