

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class UnprocessedLink : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the UnprocessedLink entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public UnprocessedLink()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public UnprocessedLink(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UnprocessedLink> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.UnprocessedLink.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnprocessedLink_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnprocessedLink_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.UnprocessedLink.DetailsClass.GetValue(this, global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.UnprocessedLink.DetailsClass.GetValue(this, global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.UnprocessedLink.DetailsClass.SetValue(this, global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string URL
        {
            get
            {
                return global::LightSwitchApplication.UnprocessedLink.DetailsClass.GetValue(this, global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.URL);
            }
            set
            {
                global::LightSwitchApplication.UnprocessedLink.DetailsClass.SetValue(this, global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.URL, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void URL_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void URL_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void URL_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.UnprocessedLink.DetailsClass.GetValue(this, global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.UnprocessedLink.DetailsClass.SetValue(this, global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.LinkSpotterUnprocessedLink> LinkSpotterUnprocessedLinks
        {
            get
            {
                return global::LightSwitchApplication.UnprocessedLink.DetailsClass.GetValue(this, global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.LinkSpotterUnprocessedLinks);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.LinkSpotterUnprocessedLink> LinkSpotterUnprocessedLinksQuery
        {
            get
            {
                return global::LightSwitchApplication.UnprocessedLink.DetailsClass.GetQuery(this, global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.LinkSpotterUnprocessedLinks);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.UnprocessedLink,
                global::LightSwitchApplication.UnprocessedLink.DetailsClass,
                global::LightSwitchApplication.UnprocessedLink.DetailsClass.IImplementation,
                global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass>.Entry
                __UnprocessedLinkEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass>.Entry(
                    global::LightSwitchApplication.UnprocessedLink.DetailsClass.__UnprocessedLink_CreateNew,
                    global::LightSwitchApplication.UnprocessedLink.DetailsClass.__UnprocessedLink_Created,
                    global::LightSwitchApplication.UnprocessedLink.DetailsClass.__UnprocessedLink_AllowSaveWithErrors);
            private static global::LightSwitchApplication.UnprocessedLink __UnprocessedLink_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UnprocessedLink> es)
            {
                return new global::LightSwitchApplication.UnprocessedLink(es);
            }
            private static void __UnprocessedLink_Created(global::LightSwitchApplication.UnprocessedLink e)
            {
                e.UnprocessedLink_Created();
            }
            private static bool __UnprocessedLink_AllowSaveWithErrors(global::LightSwitchApplication.UnprocessedLink e)
            {
                bool result = false;
                e.UnprocessedLink_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string> URL
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.URL) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink> LinkSpotterUnprocessedLinks
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.LinkSpotterUnprocessedLinks) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Title { get; set; }
                new string URL { get; set; }
                new string Description { get; set; }
                new global::System.Collections.IEnumerable LinkSpotterUnprocessedLinks { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UnprocessedLink.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, int>.Data> c, global::LightSwitchApplication.UnprocessedLink.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.UnprocessedLink e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.UnprocessedLink e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.UnprocessedLink.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.UnprocessedLink e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UnprocessedLink.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>.Data> c, global::LightSwitchApplication.UnprocessedLink.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.UnprocessedLink e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.UnprocessedLink e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.UnprocessedLink.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.UnprocessedLink.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.UnprocessedLink e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>.Entry
                    URL = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>.Entry(
                        "URL",
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._URL_Stub,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._URL_ComputeIsReadOnly,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._URL_Validate,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._URL_GetImplementationValue,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._URL_SetImplementationValue,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._URL_OnValueChanged);
                private static void _URL_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UnprocessedLink.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>.Data> c, global::LightSwitchApplication.UnprocessedLink.DetailsClass d, object sf)
                {
                    c(d, ref d._URL, sf);
                }
                private static bool _URL_ComputeIsReadOnly(global::LightSwitchApplication.UnprocessedLink e)
                {
                    bool result = false;
                    e.URL_IsReadOnly(ref result);
                    return result;
                }
                private static void _URL_Validate(global::LightSwitchApplication.UnprocessedLink e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.URL_Validate(r);
                }
                private static string _URL_GetImplementationValue(global::LightSwitchApplication.UnprocessedLink.DetailsClass d)
                {
                    return d.ImplementationEntity.URL;
                }
                private static void _URL_SetImplementationValue(global::LightSwitchApplication.UnprocessedLink.DetailsClass d, string v)
                {
                    d.ImplementationEntity.URL = v;
                }
                private static void _URL_OnValueChanged(global::LightSwitchApplication.UnprocessedLink e)
                {
                    e.URL_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UnprocessedLink.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>.Data> c, global::LightSwitchApplication.UnprocessedLink.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.UnprocessedLink e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.UnprocessedLink e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.UnprocessedLink.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.UnprocessedLink.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.UnprocessedLink e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Entry
                    LinkSpotterUnprocessedLinks = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Entry(
                        "LinkSpotterUnprocessedLinks",
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._LinkSpotterUnprocessedLinks_Stub,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._LinkSpotterUnprocessedLinks_GetReferencedEntities,
                        global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties._LinkSpotterUnprocessedLinks_GetEntityCollection);
                private static void _LinkSpotterUnprocessedLinks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UnprocessedLink.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Data> c, global::LightSwitchApplication.UnprocessedLink.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotterUnprocessedLinks, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.LinkSpotterUnprocessedLink> _LinkSpotterUnprocessedLinks_GetReferencedEntities(global::LightSwitchApplication.UnprocessedLink.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.LinkSpotterUnprocessedLink, global::LightSwitchApplication.LinkSpotterUnprocessedLink.DetailsClass>(global::LightSwitchApplication.UnprocessedLink.DetailsClass.PropertySetProperties.LinkSpotterUnprocessedLinks, ref d._LinkSpotterUnprocessedLinks);
                }
                private static global::System.Collections.IEnumerable _LinkSpotterUnprocessedLinks_GetEntityCollection(global::LightSwitchApplication.UnprocessedLink.DetailsClass d)
                {
                    return d.ImplementationEntity.LinkSpotterUnprocessedLinks;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>.Data _URL;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UnprocessedLink, global::LightSwitchApplication.UnprocessedLink.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Data _LinkSpotterUnprocessedLinks;
            
        }
    
        #endregion
    }
    
    #endregion
}
