

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Newsletter : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Newsletter entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Newsletter()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Newsletter(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Newsletter> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Newsletter.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Newsletter_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Newsletter_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Newsletter.DetailsClass.GetValue(this, global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.Newsletter.DetailsClass.GetValue(this, global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.Newsletter.DetailsClass.SetValue(this, global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.Newsletter.DetailsClass.GetValue(this, global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.Newsletter.DetailsClass.SetValue(this, global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> PublishDate
        {
            get
            {
                return global::LightSwitchApplication.Newsletter.DetailsClass.GetValue(this, global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.PublishDate);
            }
            set
            {
                global::LightSwitchApplication.Newsletter.DetailsClass.SetValue(this, global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.PublishDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PublishDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PublishDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PublishDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Link> Links
        {
            get
            {
                return global::LightSwitchApplication.Newsletter.DetailsClass.GetValue(this, global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.Links);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Link> LinksQuery
        {
            get
            {
                return global::LightSwitchApplication.Newsletter.DetailsClass.GetQuery(this, global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.Links);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Newsletter,
                global::LightSwitchApplication.Newsletter.DetailsClass,
                global::LightSwitchApplication.Newsletter.DetailsClass.IImplementation,
                global::LightSwitchApplication.Newsletter.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass>.Entry
                __NewsletterEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass>.Entry(
                    global::LightSwitchApplication.Newsletter.DetailsClass.__Newsletter_CreateNew,
                    global::LightSwitchApplication.Newsletter.DetailsClass.__Newsletter_Created,
                    global::LightSwitchApplication.Newsletter.DetailsClass.__Newsletter_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Newsletter __Newsletter_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Newsletter> es)
            {
                return new global::LightSwitchApplication.Newsletter(es);
            }
            private static void __Newsletter_Created(global::LightSwitchApplication.Newsletter e)
            {
                e.Newsletter_Created();
            }
            private static bool __Newsletter_AllowSaveWithErrors(global::LightSwitchApplication.Newsletter e)
            {
                bool result = false;
                e.Newsletter_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Newsletter.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, global::System.Nullable<global::System.DateTime>> PublishDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.PublishDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, global::LightSwitchApplication.Link> Links
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.Links) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, global::LightSwitchApplication.Link>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Name { get; set; }
                new string Description { get; set; }
                new global::System.Nullable<global::System.DateTime> PublishDate { get; set; }
                new global::System.Collections.IEnumerable Links { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Newsletter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, int>.Data> c, global::LightSwitchApplication.Newsletter.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Newsletter e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Newsletter e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Newsletter.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Newsletter e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Newsletter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, string>.Data> c, global::LightSwitchApplication.Newsletter.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.Newsletter e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.Newsletter e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.Newsletter.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.Newsletter.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.Newsletter e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Newsletter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, string>.Data> c, global::LightSwitchApplication.Newsletter.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.Newsletter e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.Newsletter e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.Newsletter.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.Newsletter.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.Newsletter e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    PublishDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "PublishDate",
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._PublishDate_Stub,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._PublishDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._PublishDate_Validate,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._PublishDate_GetImplementationValue,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._PublishDate_SetImplementationValue,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._PublishDate_OnValueChanged);
                private static void _PublishDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Newsletter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Newsletter.DetailsClass d, object sf)
                {
                    c(d, ref d._PublishDate, sf);
                }
                private static bool _PublishDate_ComputeIsReadOnly(global::LightSwitchApplication.Newsletter e)
                {
                    bool result = false;
                    e.PublishDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _PublishDate_Validate(global::LightSwitchApplication.Newsletter e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PublishDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _PublishDate_GetImplementationValue(global::LightSwitchApplication.Newsletter.DetailsClass d)
                {
                    return d.ImplementationEntity.PublishDate;
                }
                private static void _PublishDate_SetImplementationValue(global::LightSwitchApplication.Newsletter.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.PublishDate = global::LightSwitchApplication.Newsletter.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _PublishDate_OnValueChanged(global::LightSwitchApplication.Newsletter e)
                {
                    e.PublishDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, global::LightSwitchApplication.Link>.Entry
                    Links = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, global::LightSwitchApplication.Link>.Entry(
                        "Links",
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Links_Stub,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Links_GetReferencedEntities,
                        global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties._Links_GetEntityCollection);
                private static void _Links_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Newsletter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, global::LightSwitchApplication.Link>.Data> c, global::LightSwitchApplication.Newsletter.DetailsClass d, object sf)
                {
                    c(d, ref d._Links, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Link> _Links_GetReferencedEntities(global::LightSwitchApplication.Newsletter.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Link, global::LightSwitchApplication.Link.DetailsClass>(global::LightSwitchApplication.Newsletter.DetailsClass.PropertySetProperties.Links, ref d._Links);
                }
                private static global::System.Collections.IEnumerable _Links_GetEntityCollection(global::LightSwitchApplication.Newsletter.DetailsClass d)
                {
                    return d.ImplementationEntity.Links;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _PublishDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Newsletter, global::LightSwitchApplication.Newsletter.DetailsClass, global::LightSwitchApplication.Link>.Data _Links;
            
        }
    
        #endregion
    }
    
    #endregion
}
