

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class LinkSpotter : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the LinkSpotter entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LinkSpotter()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LinkSpotter(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LinkSpotter> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.LinkSpotter.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LinkSpotter_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LinkSpotter_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.LinkSpotter.DetailsClass.GetValue(this, global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FullName
        {
            get
            {
                return global::LightSwitchApplication.LinkSpotter.DetailsClass.GetValue(this, global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.FullName);
            }
            set
            {
                global::LightSwitchApplication.LinkSpotter.DetailsClass.SetValue(this, global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.FullName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FullName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FullName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FullName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string URL
        {
            get
            {
                return global::LightSwitchApplication.LinkSpotter.DetailsClass.GetValue(this, global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.URL);
            }
            set
            {
                global::LightSwitchApplication.LinkSpotter.DetailsClass.SetValue(this, global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.URL, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void URL_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void URL_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void URL_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PUID
        {
            get
            {
                return global::LightSwitchApplication.LinkSpotter.DetailsClass.GetValue(this, global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.PUID);
            }
            set
            {
                global::LightSwitchApplication.LinkSpotter.DetailsClass.SetValue(this, global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.PUID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PUID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PUID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PUID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.LinkSpotterLink> LinkSpotterLinks
        {
            get
            {
                return global::LightSwitchApplication.LinkSpotter.DetailsClass.GetValue(this, global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.LinkSpotterLinks);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.LinkSpotterLink> LinkSpotterLinksQuery
        {
            get
            {
                return global::LightSwitchApplication.LinkSpotter.DetailsClass.GetQuery(this, global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.LinkSpotterLinks);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.LinkSpotterUnprocessedLink> LinkSpotterUnprocessedLinks
        {
            get
            {
                return global::LightSwitchApplication.LinkSpotter.DetailsClass.GetValue(this, global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.LinkSpotterUnprocessedLinks);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.LinkSpotterUnprocessedLink> LinkSpotterUnprocessedLinksQuery
        {
            get
            {
                return global::LightSwitchApplication.LinkSpotter.DetailsClass.GetQuery(this, global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.LinkSpotterUnprocessedLinks);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.LinkSpotter,
                global::LightSwitchApplication.LinkSpotter.DetailsClass,
                global::LightSwitchApplication.LinkSpotter.DetailsClass.IImplementation,
                global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass>.Entry
                __LinkSpotterEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass>.Entry(
                    global::LightSwitchApplication.LinkSpotter.DetailsClass.__LinkSpotter_CreateNew,
                    global::LightSwitchApplication.LinkSpotter.DetailsClass.__LinkSpotter_Created,
                    global::LightSwitchApplication.LinkSpotter.DetailsClass.__LinkSpotter_AllowSaveWithErrors);
            private static global::LightSwitchApplication.LinkSpotter __LinkSpotter_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LinkSpotter> es)
            {
                return new global::LightSwitchApplication.LinkSpotter(es);
            }
            private static void __LinkSpotter_Created(global::LightSwitchApplication.LinkSpotter e)
            {
                e.LinkSpotter_Created();
            }
            private static bool __LinkSpotter_AllowSaveWithErrors(global::LightSwitchApplication.LinkSpotter e)
            {
                bool result = false;
                e.LinkSpotter_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string> FullName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.FullName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string> URL
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.URL) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string> PUID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.PUID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, global::LightSwitchApplication.LinkSpotterLink> LinkSpotterLinks
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.LinkSpotterLinks) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink> LinkSpotterUnprocessedLinks
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.LinkSpotterUnprocessedLinks) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string FullName { get; set; }
                new string URL { get; set; }
                new string PUID { get; set; }
                new global::System.Collections.IEnumerable LinkSpotterLinks { get; }
                new global::System.Collections.IEnumerable LinkSpotterUnprocessedLinks { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LinkSpotter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, int>.Data> c, global::LightSwitchApplication.LinkSpotter.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.LinkSpotter e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.LinkSpotter e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.LinkSpotter.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.LinkSpotter e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>.Entry
                    FullName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>.Entry(
                        "FullName",
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._FullName_Stub,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._FullName_ComputeIsReadOnly,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._FullName_Validate,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._FullName_GetImplementationValue,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._FullName_SetImplementationValue,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._FullName_OnValueChanged);
                private static void _FullName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LinkSpotter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>.Data> c, global::LightSwitchApplication.LinkSpotter.DetailsClass d, object sf)
                {
                    c(d, ref d._FullName, sf);
                }
                private static bool _FullName_ComputeIsReadOnly(global::LightSwitchApplication.LinkSpotter e)
                {
                    bool result = false;
                    e.FullName_IsReadOnly(ref result);
                    return result;
                }
                private static void _FullName_Validate(global::LightSwitchApplication.LinkSpotter e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FullName_Validate(r);
                }
                private static string _FullName_GetImplementationValue(global::LightSwitchApplication.LinkSpotter.DetailsClass d)
                {
                    return d.ImplementationEntity.FullName;
                }
                private static void _FullName_SetImplementationValue(global::LightSwitchApplication.LinkSpotter.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FullName = v;
                }
                private static void _FullName_OnValueChanged(global::LightSwitchApplication.LinkSpotter e)
                {
                    e.FullName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>.Entry
                    URL = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>.Entry(
                        "URL",
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._URL_Stub,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._URL_ComputeIsReadOnly,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._URL_Validate,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._URL_GetImplementationValue,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._URL_SetImplementationValue,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._URL_OnValueChanged);
                private static void _URL_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LinkSpotter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>.Data> c, global::LightSwitchApplication.LinkSpotter.DetailsClass d, object sf)
                {
                    c(d, ref d._URL, sf);
                }
                private static bool _URL_ComputeIsReadOnly(global::LightSwitchApplication.LinkSpotter e)
                {
                    bool result = false;
                    e.URL_IsReadOnly(ref result);
                    return result;
                }
                private static void _URL_Validate(global::LightSwitchApplication.LinkSpotter e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.URL_Validate(r);
                }
                private static string _URL_GetImplementationValue(global::LightSwitchApplication.LinkSpotter.DetailsClass d)
                {
                    return d.ImplementationEntity.URL;
                }
                private static void _URL_SetImplementationValue(global::LightSwitchApplication.LinkSpotter.DetailsClass d, string v)
                {
                    d.ImplementationEntity.URL = v;
                }
                private static void _URL_OnValueChanged(global::LightSwitchApplication.LinkSpotter e)
                {
                    e.URL_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>.Entry
                    PUID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>.Entry(
                        "PUID",
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._PUID_Stub,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._PUID_ComputeIsReadOnly,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._PUID_Validate,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._PUID_GetImplementationValue,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._PUID_SetImplementationValue,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._PUID_OnValueChanged);
                private static void _PUID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LinkSpotter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>.Data> c, global::LightSwitchApplication.LinkSpotter.DetailsClass d, object sf)
                {
                    c(d, ref d._PUID, sf);
                }
                private static bool _PUID_ComputeIsReadOnly(global::LightSwitchApplication.LinkSpotter e)
                {
                    bool result = false;
                    e.PUID_IsReadOnly(ref result);
                    return result;
                }
                private static void _PUID_Validate(global::LightSwitchApplication.LinkSpotter e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PUID_Validate(r);
                }
                private static string _PUID_GetImplementationValue(global::LightSwitchApplication.LinkSpotter.DetailsClass d)
                {
                    return d.ImplementationEntity.PUID;
                }
                private static void _PUID_SetImplementationValue(global::LightSwitchApplication.LinkSpotter.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PUID = v;
                }
                private static void _PUID_OnValueChanged(global::LightSwitchApplication.LinkSpotter e)
                {
                    e.PUID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Entry
                    LinkSpotterLinks = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Entry(
                        "LinkSpotterLinks",
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._LinkSpotterLinks_Stub,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._LinkSpotterLinks_GetReferencedEntities,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._LinkSpotterLinks_GetEntityCollection);
                private static void _LinkSpotterLinks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LinkSpotter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Data> c, global::LightSwitchApplication.LinkSpotter.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotterLinks, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.LinkSpotterLink> _LinkSpotterLinks_GetReferencedEntities(global::LightSwitchApplication.LinkSpotter.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.LinkSpotterLink, global::LightSwitchApplication.LinkSpotterLink.DetailsClass>(global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.LinkSpotterLinks, ref d._LinkSpotterLinks);
                }
                private static global::System.Collections.IEnumerable _LinkSpotterLinks_GetEntityCollection(global::LightSwitchApplication.LinkSpotter.DetailsClass d)
                {
                    return d.ImplementationEntity.LinkSpotterLinks;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Entry
                    LinkSpotterUnprocessedLinks = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Entry(
                        "LinkSpotterUnprocessedLinks",
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._LinkSpotterUnprocessedLinks_Stub,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._LinkSpotterUnprocessedLinks_GetReferencedEntities,
                        global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties._LinkSpotterUnprocessedLinks_GetEntityCollection);
                private static void _LinkSpotterUnprocessedLinks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LinkSpotter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Data> c, global::LightSwitchApplication.LinkSpotter.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkSpotterUnprocessedLinks, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.LinkSpotterUnprocessedLink> _LinkSpotterUnprocessedLinks_GetReferencedEntities(global::LightSwitchApplication.LinkSpotter.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.LinkSpotterUnprocessedLink, global::LightSwitchApplication.LinkSpotterUnprocessedLink.DetailsClass>(global::LightSwitchApplication.LinkSpotter.DetailsClass.PropertySetProperties.LinkSpotterUnprocessedLinks, ref d._LinkSpotterUnprocessedLinks);
                }
                private static global::System.Collections.IEnumerable _LinkSpotterUnprocessedLinks_GetEntityCollection(global::LightSwitchApplication.LinkSpotter.DetailsClass d)
                {
                    return d.ImplementationEntity.LinkSpotterUnprocessedLinks;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>.Data _FullName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>.Data _URL;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, string>.Data _PUID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, global::LightSwitchApplication.LinkSpotterLink>.Data _LinkSpotterLinks;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LinkSpotter, global::LightSwitchApplication.LinkSpotter.DetailsClass, global::LightSwitchApplication.LinkSpotterUnprocessedLink>.Data _LinkSpotterUnprocessedLinks;
            
        }
    
        #endregion
    }
    
    #endregion
}
