

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Category : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Category entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Category()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Category(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Category> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Category.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Category_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Category_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Category.DetailsClass.GetValue(this, global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.Category.DetailsClass.GetValue(this, global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.Category.DetailsClass.SetValue(this, global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SortOrder
        {
            get
            {
                return global::LightSwitchApplication.Category.DetailsClass.GetValue(this, global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties.SortOrder);
            }
            set
            {
                global::LightSwitchApplication.Category.DetailsClass.SetValue(this, global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties.SortOrder, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SortOrder_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SortOrder_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SortOrder_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.LinkCategory> LinkCategories
        {
            get
            {
                return global::LightSwitchApplication.Category.DetailsClass.GetValue(this, global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties.LinkCategories);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.LinkCategory> LinkCategoriesQuery
        {
            get
            {
                return global::LightSwitchApplication.Category.DetailsClass.GetQuery(this, global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties.LinkCategories);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Category,
                global::LightSwitchApplication.Category.DetailsClass,
                global::LightSwitchApplication.Category.DetailsClass.IImplementation,
                global::LightSwitchApplication.Category.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass>.Entry
                __CategoryEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass>.Entry(
                    global::LightSwitchApplication.Category.DetailsClass.__Category_CreateNew,
                    global::LightSwitchApplication.Category.DetailsClass.__Category_Created,
                    global::LightSwitchApplication.Category.DetailsClass.__Category_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Category __Category_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Category> es)
            {
                return new global::LightSwitchApplication.Category(es);
            }
            private static void __Category_Created(global::LightSwitchApplication.Category e)
            {
                e.Category_Created();
            }
            private static bool __Category_AllowSaveWithErrors(global::LightSwitchApplication.Category e)
            {
                bool result = false;
                e.Category_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Category.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, int> SortOrder
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties.SortOrder) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, global::LightSwitchApplication.LinkCategory> LinkCategories
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties.LinkCategories) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, global::LightSwitchApplication.LinkCategory>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Name { get; set; }
                new int SortOrder { get; set; }
                new global::System.Collections.IEnumerable LinkCategories { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Category.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, int>.Data> c, global::LightSwitchApplication.Category.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Category e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Category e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Category.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Category e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Category.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, string>.Data> c, global::LightSwitchApplication.Category.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.Category e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.Category e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.Category.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.Category.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.Category e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, int>.Entry
                    SortOrder = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, int>.Entry(
                        "SortOrder",
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._SortOrder_Stub,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._SortOrder_ComputeIsReadOnly,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._SortOrder_Validate,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._SortOrder_GetImplementationValue,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._SortOrder_SetImplementationValue,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._SortOrder_OnValueChanged);
                private static void _SortOrder_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Category.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, int>.Data> c, global::LightSwitchApplication.Category.DetailsClass d, object sf)
                {
                    c(d, ref d._SortOrder, sf);
                }
                private static bool _SortOrder_ComputeIsReadOnly(global::LightSwitchApplication.Category e)
                {
                    bool result = false;
                    e.SortOrder_IsReadOnly(ref result);
                    return result;
                }
                private static void _SortOrder_Validate(global::LightSwitchApplication.Category e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SortOrder_Validate(r);
                }
                private static int _SortOrder_GetImplementationValue(global::LightSwitchApplication.Category.DetailsClass d)
                {
                    return d.ImplementationEntity.SortOrder;
                }
                private static void _SortOrder_SetImplementationValue(global::LightSwitchApplication.Category.DetailsClass d, int v)
                {
                    d.ImplementationEntity.SortOrder = v;
                }
                private static void _SortOrder_OnValueChanged(global::LightSwitchApplication.Category e)
                {
                    e.SortOrder_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, global::LightSwitchApplication.LinkCategory>.Entry
                    LinkCategories = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, global::LightSwitchApplication.LinkCategory>.Entry(
                        "LinkCategories",
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._LinkCategories_Stub,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._LinkCategories_GetReferencedEntities,
                        global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties._LinkCategories_GetEntityCollection);
                private static void _LinkCategories_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Category.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, global::LightSwitchApplication.LinkCategory>.Data> c, global::LightSwitchApplication.Category.DetailsClass d, object sf)
                {
                    c(d, ref d._LinkCategories, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.LinkCategory> _LinkCategories_GetReferencedEntities(global::LightSwitchApplication.Category.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.LinkCategory, global::LightSwitchApplication.LinkCategory.DetailsClass>(global::LightSwitchApplication.Category.DetailsClass.PropertySetProperties.LinkCategories, ref d._LinkCategories);
                }
                private static global::System.Collections.IEnumerable _LinkCategories_GetEntityCollection(global::LightSwitchApplication.Category.DetailsClass d)
                {
                    return d.ImplementationEntity.LinkCategories;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, int>.Data _SortOrder;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass, global::LightSwitchApplication.LinkCategory>.Data _LinkCategories;
            
        }
    
        #endregion
    }
    
    #endregion
}
